apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/dani-izquierdo95-gmail-com/dotnetapp:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/dani-izquierdo95-gmail-com/dotnetapp:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: dotnetapp
        chartPath: charts/dotnetapp
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/dani-izquierdo95-gmail-com/dotnetapp"
          image.tag: "{{.DIGEST_HEX}}"
